
corpus_id: 3
customer_id: 1169579801

search_title: "Hackernews search"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7

summary_prompt_name: vectara-summary-ext-v1.4.0
#summary_prompt_name: vectara-summary-ext-v1.2.0

enable_source_filters: False

